# Generated by Django 5.1.6 on 2025-02-09 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_code',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='admin_code',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='user',
            new_name='manager_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='email',
        ),
        migrations.RemoveField(
            model_name='college',
            name='name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='password',
        ),
        migrations.AddField(
            model_name='admin',
            name='Sno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='Sno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Sno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='Sno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Sno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
